name: Update Submodules

on:
    push:
        branches: [ main ]
    workflow_dispatch:
    
jobs:
    update_submodules:
        name: Update Submodules
        runs-on: ubuntu-latest        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  submodules: false

            - name: Update Submodules
              run: |
                  echo daddy chill
